export const COLOR_PALETTES = [
  {
    name: "Ocean Blue",
    colors: {
      primaryColor: "#2563eb",
      backgroundColor: "#f0f6ff",
      backgroundColorDark: "#18181b",
      foregroundColor: "#1e293b",
      foregroundColorDark: "#f4f4f5",
      secondaryColor: "#38bdf8",
      secondaryColorDark: "#818cf8",
      buttonColor: "#2563eb",
      buttonColorDark: "#3b82f6",
      buttonTextColor: "#ffffff",
      buttonTextColorDark: "#f4f4f5",
      cardBackgroundColor: "#e0e7ef",
      cardBackgroundColorDark: "#27272a",
      linkColor: "#2563eb",
      linkColorDark: "#38bdf8",
      navbarColor: "#ffffff",
      navbarColorDark: "#18181b",
      footerColor: "#e0e7ef",
      footerColorDark: "#27272a",
      borderRadius: "0.5rem",
      fontFamily: "Inter",
    },
  },
  {
    name: "Sunset",
    colors: {
      primaryColor: "#f59e42",
      backgroundColor: "#fff7ed",
      backgroundColorDark: "#2d1a0b",
      foregroundColor: "#7c2d12",
      foregroundColorDark: "#ffe7c2",
      secondaryColor: "#fbbf24",
      secondaryColorDark: "#f59e42",
      buttonColor: "#ea580c",
      buttonColorDark: "#f59e42",
      buttonTextColor: "#fff7ed",
      buttonTextColorDark: "#2d1a0b",
      cardBackgroundColor: "#ffedd5",
      cardBackgroundColorDark: "#3b2412",
      linkColor: "#ea580c",
      linkColorDark: "#fbbf24",
      navbarColor: "#fff7ed",
      navbarColorDark: "#2d1a0b",
      footerColor: "#ffedd5",
      footerColorDark: "#3b2412",
      borderRadius: "0.5rem",
      fontFamily: "Poppins",
    },
  },
  {
    name: "Emerald",
    colors: {
      primaryColor: "#10b981",
      backgroundColor: "#ecfdf5",
      backgroundColorDark: "#052e16",
      foregroundColor: "#064e3b",
      foregroundColorDark: "#d1fae5",
      secondaryColor: "#6ee7b7",
      secondaryColorDark: "#10b981",
      buttonColor: "#10b981",
      buttonColorDark: "#6ee7b7",
      buttonTextColor: "#ffffff",
      buttonTextColorDark: "#052e16",
      cardBackgroundColor: "#d1fae5",
      cardBackgroundColorDark: "#134e4a",
      linkColor: "#10b981",
      linkColorDark: "#6ee7b7",
      navbarColor: "#ffffff",
      navbarColorDark: "#052e16",
      footerColor: "#d1fae5",
      footerColorDark: "#134e4a",
      borderRadius: "0.5rem",
      fontFamily: "Montserrat",
    },
  },
  {
    name: "Royal Purple",
    colors: {
      primaryColor: "#8b5cf6",
      backgroundColor: "#f5f3ff",
      backgroundColorDark: "#2e1065",
      foregroundColor: "#2e1065",
      foregroundColorDark: "#ede9fe",
      secondaryColor: "#a78bfa",
      secondaryColorDark: "#8b5cf6",
      buttonColor: "#7c3aed",
      buttonColorDark: "#a78bfa",
      buttonTextColor: "#f5f3ff",
      buttonTextColorDark: "#2e1065",
      cardBackgroundColor: "#ede9fe",
      cardBackgroundColorDark: "#3b0764",
      linkColor: "#7c3aed",
      linkColorDark: "#a78bfa",
      navbarColor: "#f5f3ff",
      navbarColorDark: "#2e1065",
      footerColor: "#ede9fe",
      footerColorDark: "#3b0764",
      borderRadius: "0.5rem",
      fontFamily: "Roboto",
    },
  },
  {
    name: "Classic Dark",
    colors: {
      primaryColor: "#3b82f6",
      backgroundColor: "#f4f4f5",
      backgroundColorDark: "#18181b",
      foregroundColor: "#18181b",
      foregroundColorDark: "#f4f4f5",
      secondaryColor: "#818cf8",
      secondaryColorDark: "#6366f1",
      buttonColor: "#3b82f6",
      buttonColorDark: "#2563eb",
      buttonTextColor: "#f4f4f5",
      buttonTextColorDark: "#18181b",
      cardBackgroundColor: "#e5e7eb",
      cardBackgroundColorDark: "#27272a",
      linkColor: "#818cf8",
      linkColorDark: "#3b82f6",
      navbarColor: "#f4f4f5",
      navbarColorDark: "#18181b",
      footerColor: "#e5e7eb",
      footerColorDark: "#27272a",
      borderRadius: "0.5rem",
      fontFamily: "Open Sans",
    },
  },
  {
    name: "Mint Coral",
    colors: {
      primaryColor: "#ff6f61",
      backgroundColor: "#f0fff7",
      backgroundColorDark: "#1a2327",
      foregroundColor: "#1a2327",
      foregroundColorDark: "#f0fff7",
      secondaryColor: "#2ec4b6",
      secondaryColorDark: "#ff6f61",
      buttonColor: "#2ec4b6",
      buttonColorDark: "#ff6f61",
      buttonTextColor: "#ffffff",
      buttonTextColorDark: "#1a2327",
      cardBackgroundColor: "#e0f7fa",
      cardBackgroundColorDark: "#22303a",
      linkColor: "#ff6f61",
      linkColorDark: "#2ec4b6",
      navbarColor: "#f0fff7",
      navbarColorDark: "#1a2327",
      footerColor: "#e0f7fa",
      footerColorDark: "#22303a",
      borderRadius: "0.5rem",
      fontFamily: "Quicksand",
    },
  },
  {
    name: "Cyber Lime",
    colors: {
      primaryColor: "#39ff14", // vivid lime green
      backgroundColor: "#18181b", // dark neutral
      backgroundColorDark: "#101014", // even darker neutral
      foregroundColor: "#f4f4f5", // light text
      foregroundColorDark: "#e0e0e0", // slightly dimmed light text
      secondaryColor: "#00fff7", // neon cyan
      secondaryColorDark: "#39ff14", // neon lime
      buttonColor: "#39ff14",
      buttonColorDark: "#00fff7",
      buttonTextColor: "#18181b",
      buttonTextColorDark: "#101014",
      cardBackgroundColor: "#23272a",
      cardBackgroundColorDark: "#18181b",
      linkColor: "#00fff7",
      linkColorDark: "#39ff14",
      navbarColor: "#18181b",
      navbarColorDark: "#101014",
      footerColor: "#23272a",
      footerColorDark: "#18181b",
      borderRadius: "0.5rem",
      fontFamily: "Orbitron",
    },
  },

  {
    name: "Blush Rose",
    colors: {
      primaryColor: "#e66767",
      backgroundColor: "#fff5f7",
      backgroundColorDark: "#2a1a1f",
      foregroundColor: "#4a1c2a",
      foregroundColorDark: "#ffe4ec",
      secondaryColor: "#f9bec7",
      secondaryColorDark: "#e66767",
      buttonColor: "#d6336c",
      buttonColorDark: "#f9bec7",
      buttonTextColor: "#ffffff",
      buttonTextColorDark: "#2a1a1f",
      cardBackgroundColor: "#ffe4ec",
      cardBackgroundColorDark: "#3b2630",
      linkColor: "#d6336c",
      linkColorDark: "#f9bec7",
      navbarColor: "#fff5f7",
      navbarColorDark: "#2a1a1f",
      footerColor: "#ffe4ec",
      footerColorDark: "#3b2630",
      borderRadius: "0.5rem",
      fontFamily: "Playfair Display",
    },
  },

  {
    name: "Desert Clay",
    colors: {
      primaryColor: "#c08457",
      backgroundColor: "#fdf6f0",
      backgroundColorDark: "#1e1a17",
      foregroundColor: "#3e2c23",
      foregroundColorDark: "#f5ebe0",
      secondaryColor: "#e3b77b",
      secondaryColorDark: "#c08457",
      buttonColor: "#ab6e46",
      buttonColorDark: "#e3b77b",
      buttonTextColor: "#ffffff",
      buttonTextColorDark: "#1e1a17",
      cardBackgroundColor: "#f5ebe0",
      cardBackgroundColorDark: "#2e2622",
      linkColor: "#ab6e46",
      linkColorDark: "#e3b77b",
      navbarColor: "#fdf6f0",
      navbarColorDark: "#1e1a17",
      footerColor: "#f5ebe0",
      footerColorDark: "#2e2622",
      borderRadius: "0.5rem",
      fontFamily: "Lora",
    },
  }
  
  
]; 